networks: 
  default:
    external: true
    name: servisofts

services:
  strongswan:
    image: servisofts/strongswan
    build: .
    stdin_open: true
    tty: true
    privileged: true
    networks:
      default:
        ipv4_address: 192.168.3.11
    volumes:
      - ./conf:/app/conf
      - /etc/localtime:/etc/localtime:ro
    
