services:
  strongswan:
    image: servisofts/strongswan
    build: .
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - ./env/:/env/
      - ./env/pki/:/app/pki/
      - ./env/cacerts/:/etc/ipsec.d/cacerts/
    command: sh /env/create_certs.sh && sh /env/start.sh
    
    